### ISSUE TITLE
Code Reorganization and Cleanup

### ISSUE THREAD

**Issue by ali01** [athenalabs/acorn-player#58]
# acorn.js
- simplify initialization of global `acorn` object;
  do what we do with engine
- factor out utility code to separate file
  - acorn.{options,errors,types,util} should not clutter acorn.js
  - create util.js
  - create util_regex.js
- unify acorn.util.sync with acorn.Model.{fetch,save}
- clarify and document distinction between data and shell data
# shells
- each shell file should encapsulate its contents in a closure
- clarify and document use and need of shellRegistry

**Comment by alive-zk** [comment]
- EngineView equivalent for acorn
