### ISSUE TITLE
vimeo shell: edit view: duration is broken

### ISSUE THREAD

**Issue by tenedor** [athenalabs/acorn-player#75]
I see things like this:
![](http://static.benet.ai/skitch_tenedor/acorn_-_multimedia_wrapper-20121121-184006.jpg)

and get errors like this:
![](http://static.benet.ai/skitch_tenedor/acorn_-_multimedia_wrapper-20121121-184134.jpg)

**Comment by jbenet** [comment]
rpashctaaf. rah-PASH-ktahf. Brilliant.
