### ISSUE TITLE
Thumbnails are broken

### ISSUE THREAD

**Issue by tenedor** [athenalabs/acorn-player#8]
c/o @jbenet:

except for youtube.

**Comment by tenedor** [comment]
c/o @jbenet, referring to the state of code on 8/15/12:

With respect to Vimeo thumbnails, when the shell gets swapped out, the `generateThumbnailLink` call gets entirely skipped because the swap happens when `editabletext.save` calls `link()`, before the `EditView.onSave` is called.  All works fine when there is no swap (try editing a VimeoShell (i.e. edit and enter, don't change it)).

It seems that the flow of calls needs to be adjusted to either:
- call `generateThumbnailLink` before swapping
- call `generateThumbnailLink` after swapping
- call `generateThumbnailLink` whenever it loads/renders without a thumbnail

The third is most robust + most hacky, imo. 2 seems the most reasonable given current way things work? Not sure. May be worth rethinking how thumbnails get generated.

**Comment by tenedor** [comment]
Note that a link shell given a link to another acorn does not generate a thumbnail corresponding to that acorn

**Comment by alive-zk** [comment]
fixed in PR #27
